/**
   * This file is autogenerated.
   * You should not edit it manually or your changes might be overwritten.
   */
  import { GenericModulesDeclaration } from "~~/utils/scaffold-move/module";

  const deployedModules = {
    2:{
  "onchain_bio": {
    "bytecode": "0xa11ceb0b0700000a0a010006020608030e1205201307334a087d4010bd01410afe01090c8702360dbd020200000104010700010e000103070000060001000102080203000100090305000103060c080108010001060c01050108000108010b6f6e636861696e5f62696f0342696f046e616d6506537472696e6706737472696e670362696f087265676973746572067369676e65720a616464726573735f6f66076765745f62696f5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d000000000000000000000000000000000000000000000000000000000000000114636f6d70696c6174696f6e5f6d65746164617461090003322e3003322e31126170746f733a3a6d657461646174615f76310e000001076765745f62696f010100000202020801050801000104010004110a0011012900030505090a0011012c00010b010b0212000c030b000b032d0002020100010001050b002b0010001402000100",
    "abi": {
      "address": "0x5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d",
      "name": "onchain_bio",
      "friends": [],
      "exposed_functions": [
        {
          "name": "register",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer",
            "0x1::string::String",
            "0x1::string::String"
          ],
          "return": []
        },
        {
          "name": "get_bio",
          "visibility": "public",
          "is_entry": false,
          "is_view": true,
          "generic_type_params": [],
          "params": [
            "address"
          ],
          "return": [
            "0x1::string::String"
          ]
        }
      ],
      "structs": [
        {
          "name": "Bio",
          "is_native": false,
          "is_event": false,
          "abilities": [
            "drop",
            "store",
            "key"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "name",
              "type": "0x1::string::String"
            },
            {
              "name": "bio",
              "type": "0x1::string::String"
            }
          ]
        }
      ]
    }
  },
  "onchain_poems": {
    "bytecode": "0xa11ceb0b0700000a0a010004020408030c0c051812072a4c08764010b601590a8f020c0c9b02260dc102020000010400010e000103070000070001000100080304000104060c0801080108010001080001050108010d6f6e636861696e5f706f656d730b496e736372697074696f6e04706f656d06537472696e6706737472696e67057469746c6506617574686f72087265676973746572086765745f706f656d5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d000000000000000000000000000000000000000000000000000000000000000114636f6d70696c6174696f6e5f6d65746164617461090003322e3003322e31126170746f733a3a6d657461646174615f7631260101000000000000000d455f414c52454144595f484153000001086765745f706f656d0101000002030208010508010608010001040002090b010b020b0312000c040b000b042d0002010100010001050b002b0010001402000000",
    "abi": {
      "address": "0x5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d",
      "name": "onchain_poems",
      "friends": [],
      "exposed_functions": [
        {
          "name": "register",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String"
          ],
          "return": []
        },
        {
          "name": "get_poem",
          "visibility": "public",
          "is_entry": false,
          "is_view": true,
          "generic_type_params": [],
          "params": [
            "address"
          ],
          "return": [
            "0x1::string::String"
          ]
        }
      ],
      "structs": [
        {
          "name": "Inscription",
          "is_native": false,
          "is_event": false,
          "abilities": [
            "drop",
            "store",
            "key"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "poem",
              "type": "0x1::string::String"
            },
            {
              "name": "title",
              "type": "0x1::string::String"
            },
            {
              "name": "author",
              "type": "0x1::string::String"
            }
          ]
        }
      ]
    }
  },
  "onchain_poems_with_table": {
    "bytecode": "0xa11ceb0b0700000a0b01000a020a14031e29044706054d3b078801bb0108c30240108303590adc031c0cf803780df0040400000106010c010f0112000107000105070000090800020b040203010001000e00010001031002030001021105010203020104130701010601001402010001021501090203040102040306050404060c0801080108010001060c01050203080003070b0302090009010900090101080001090005050708020308000703010b030209000901010802186f6e636861696e5f706f656d735f776974685f7461626c6504506f656d07706f656d5f6964076164647265737304706f656d06537472696e6706737472696e67057469746c6506617574686f7208506f656d4c69737405706f656d73055461626c65057461626c650c706f656d5f636f756e7465720b6372656174655f706f656d067369676e65720a616464726573735f6f6606757073657274056576656e7404656d6974106372656174655f706f656d5f6c697374036e65775d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d000000000000000000000000000000000000000000000000000000000000000114636f6d70696c6174696f6e5f6d65746164617461090003322e3003322e31126170746f733a3a6d657461646174615f76312601010000000000000011455f4e4f545f494e495449414c495a4544000104506f656d01040000000205020303050408010708010808010202020a0b03020308000d03000104010108260b0011010c040a04290104240a042a010c050a05100014060100000000000000160c060a060b040b010b020b0312000c070a050f010a060a0738000b050f000c080b060b08150b0738010206010000000000000027040104000a08380206000000000000000012010c010b000b012d01020101010000",
    "abi": {
      "address": "0x5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d",
      "name": "onchain_poems_with_table",
      "friends": [],
      "exposed_functions": [
        {
          "name": "create_poem",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String"
          ],
          "return": []
        },
        {
          "name": "create_poem_list",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer"
          ],
          "return": []
        }
      ],
      "structs": [
        {
          "name": "Poem",
          "is_native": false,
          "is_event": true,
          "abilities": [
            "copy",
            "drop",
            "store"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "poem_id",
              "type": "u64"
            },
            {
              "name": "address",
              "type": "address"
            },
            {
              "name": "poem",
              "type": "0x1::string::String"
            },
            {
              "name": "title",
              "type": "0x1::string::String"
            },
            {
              "name": "author",
              "type": "0x1::string::String"
            }
          ]
        },
        {
          "name": "PoemList",
          "is_native": false,
          "is_event": false,
          "abilities": [
            "key"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "poems",
              "type": "0x1::table::Table<u64, 0x5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d::onchain_poems_with_table::Poem>"
            },
            {
              "name": "poem_counter",
              "type": "u64"
            }
          ]
        }
      ]
    }
  }
},250:{
  "onchain_bio": {
    "bytecode": "0xa11ceb0b060000000a010006020608030e0f051d1307304a087a4010ba01220adc01090ce501340d99020200000101010200030e0002040700000500010000060203000109050000010501080103060c080108010001080001060c0b6f6e636861696e5f62696f067369676e657206737472696e670342696f06537472696e67076765745f62696f087265676973746572046e616d650362696f0a616464726573735f6f665d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d0000000000000000000000000000000000000000000000000000000000000001126170746f733a3a6d657461646174615f76310e000001076765745f62696f010100000202070801080801000100010003050b002b0010001402010104010004100a001102290004080a0011022c00010b010b0212000c030b000b032d0002000100",
    "abi": {
      "address": "0x5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d",
      "name": "onchain_bio",
      "friends": [],
      "exposed_functions": [
        {
          "name": "get_bio",
          "visibility": "public",
          "is_entry": false,
          "is_view": true,
          "generic_type_params": [],
          "params": [
            "address"
          ],
          "return": [
            "0x1::string::String"
          ]
        },
        {
          "name": "register",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer",
            "0x1::string::String",
            "0x1::string::String"
          ],
          "return": []
        }
      ],
      "structs": [
        {
          "name": "Bio",
          "is_native": false,
          "abilities": [
            "drop",
            "store",
            "key"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "name",
              "type": "0x1::string::String"
            },
            {
              "name": "bio",
              "type": "0x1::string::String"
            }
          ]
        }
      ]
    }
  },
  "onchain_poems": {
    "bytecode": "0xa11ceb0b060000000b010004020408030c0a05161207284c08744006b4010a10be013a0af8010c0c8402260daa02020000010100020e000103070000040001000005020300010501080104060c080108010801000108000d6f6e636861696e5f706f656d7306737472696e670b496e736372697074696f6e06537472696e67086765745f706f656d08726567697374657204706f656d057469746c6506617574686f725d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d000000000000000000000000000000000000000000000000000000000000000103080100000000000000126170746f733a3a6d657461646174615f7631260101000000000000000d455f414c52454144595f484153000001086765745f706f656d010100000203060801070801080801000100010003050b002b00100014020101040004090b010b020b0312000c040b000b042d0002000000",
    "abi": {
      "address": "0x5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d",
      "name": "onchain_poems",
      "friends": [],
      "exposed_functions": [
        {
          "name": "get_poem",
          "visibility": "public",
          "is_entry": false,
          "is_view": true,
          "generic_type_params": [],
          "params": [
            "address"
          ],
          "return": [
            "0x1::string::String"
          ]
        },
        {
          "name": "register",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String"
          ],
          "return": []
        }
      ],
      "structs": [
        {
          "name": "Inscription",
          "is_native": false,
          "abilities": [
            "drop",
            "store",
            "key"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "poem",
              "type": "0x1::string::String"
            },
            {
              "name": "title",
              "type": "0x1::string::String"
            },
            {
              "name": "author",
              "type": "0x1::string::String"
            }
          ]
        }
      ]
    }
  },
  "onchain_poems_with_table": {
    "bytecode": "0xa11ceb0b060000000c01000a020a14031e23044106054739078001bb0108bb024006fb020a1085033a0abf031c0cdb036f0dca0404000001010102010301040005070000060800030707000410040203010001000800010000090201000212020400041306010203020114080101060415010a02030403050407050504060c0802080208020001060c040308000708010501050203080003070b03020900090109000901010800010900010801010b030209000901186f6e636861696e5f706f656d735f776974685f7461626c65056576656e74067369676e657206737472696e67057461626c6504506f656d08506f656d4c69737406537472696e670b6372656174655f706f656d106372656174655f706f656d5f6c69737407706f656d5f6964076164647265737304706f656d057469746c6506617574686f7205706f656d73055461626c650c706f656d5f636f756e7465720a616464726573735f6f660675707365727404656d6974036e65775d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d000000000000000000000000000000000000000000000000000000000000000103080100000000000000126170746f733a3a6d657461646174615f76312601010000000000000011455f4e4f545f494e495449414c495a4544000104506f656d010400000002050a030b050c08020d08020e08020102020f0b03020308001103000104010103250b0011020c070a072901040705090700270a072a010c060a06100014060100000000000000160c040a040b070b010b020b0312000c050a060f010a040a0538000b040b060f00150b05380102010104000908380206000000000000000012010c010b000b012d01020101010000",
    "abi": {
      "address": "0x5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d",
      "name": "onchain_poems_with_table",
      "friends": [],
      "exposed_functions": [
        {
          "name": "create_poem",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer",
            "0x1::string::String",
            "0x1::string::String",
            "0x1::string::String"
          ],
          "return": []
        },
        {
          "name": "create_poem_list",
          "visibility": "public",
          "is_entry": true,
          "is_view": false,
          "generic_type_params": [],
          "params": [
            "&signer"
          ],
          "return": []
        }
      ],
      "structs": [
        {
          "name": "Poem",
          "is_native": false,
          "abilities": [
            "copy",
            "drop",
            "store"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "poem_id",
              "type": "u64"
            },
            {
              "name": "address",
              "type": "address"
            },
            {
              "name": "poem",
              "type": "0x1::string::String"
            },
            {
              "name": "title",
              "type": "0x1::string::String"
            },
            {
              "name": "author",
              "type": "0x1::string::String"
            }
          ]
        },
        {
          "name": "PoemList",
          "is_native": false,
          "abilities": [
            "key"
          ],
          "generic_type_params": [],
          "fields": [
            {
              "name": "poems",
              "type": "0x1::table::Table<u64, 0x5d2c589056728b30e3e644d5dff3b999433e3f1648aa622bbeb9027d7310d88d::onchain_poems_with_table::Poem>"
            },
            {
              "name": "poem_counter",
              "type": "u64"
            }
          ]
        }
      ]
    }
  }
},
  } as const;

  export default deployedModules satisfies GenericModulesDeclaration;