// This file is autogenerated - do not edit manually, your changes might be overwritten
import { GenericModulesDeclaration } from "~~/utils/scaffold-iota/module";

const deployedModules = {
  devnet: {},
  testnet: {},
} as const;

export default deployedModules satisfies GenericModulesDeclaration;
